export enum Unit {
  Gram = 'g',
  Kg = 'kg',
  Ml = 'ml',
  L = 'l',
  Piece = 'pcs',
  Teaspoon = 'tsp',
  Tablespoon = 'tbsp',
  Cup = 'cup',
}

export enum Category {
  Appetizer = 'Appetizer',
  MainCourse = 'Main course',
  Dessert = 'Dessert',
  Snack = 'Snack',
}

export enum DietType {
  Omnivore = 'Omnivore',
  Vegetarian = 'Vegetarian',
  Vegan = 'Vegan',
}

export enum MealTime {
  Breakfast = 'Breakfast',
  Lunch = 'Lunch',
  Dinner = 'Dinner',
  Brunch = 'Brunch',
  AfternoonTea = 'Afternoon Tea',
  Barbecue = 'Barbecue',
}

export enum Season {
  Spring = 'Spring',
  Summer = 'Summer',
  Autumn = 'Autumn',
  Winter = 'Winter',
}

export enum Holiday {
  Easter = 'Easter',
  Oktoberfest = 'Oktoberfest',
  Halloween = 'Halloween',
  Thanksgiving = 'Thanksgiving',
  Christmas = 'Christmas',
  NewYearsEve = 'New Years Eve',
  ValentinesDay = 'Valentines Day',
  MothersDay = 'Mothers Day',
  FathersDay = 'Fathers Day',
  Ramadan = 'Ramadan',
  Hanukkah = 'Hanukkah',
  Diwali = 'Diwali',
}

export enum Occasion {
  Birthday = 'Birthday',
  StreetFood = 'Street Food',
  Picnic = 'Picnic',
  Wedding = 'Wedding',
  Anniversary = 'Anniversary',
}

export enum Continent {
  Europe = 'Europe',
  NorthAmerica = 'North America',
  CentralAmerica = 'Central America',
  SouthAmerica = 'South America',
  Africa = 'Africa',
  Asia = 'Asia',
  Oceania = 'Oceania',
}

export enum Country {
  // Europe
  Spain = 'Spain',
  Portugal = 'Portugal',
  UnitedKingdom = 'United Kingdom',
  Italy = 'Italy',
  Greece = 'Greece',
  Netherlands = 'Netherlands',
  Belgium = 'Belgium',
  Austria = 'Austria',
  Switzerland = 'Switzerland',
  Germany = 'Germany',
  France = 'France',

  // North America
  Canada = 'Canada',
  USA = 'USA',
  Mexico = 'Mexico',

  // Central America
  ElSalvador = 'El Salvador',
  CostaRica = 'Costa Rica',
  Nicaragua = 'Nicaragua',
  Cuba = 'Cuba',
  PuertoRico = 'Puerto Rico',

  // South America
  Argentina = 'Argentina',
  Ecuador = 'Ecuador',
  Chile = 'Chile',
  Peru = 'Peru',
  Brazil = 'Brazil',
  Colombia = 'Colombia',
  Venezuela = 'Venezuela',
  Bolivia = 'Bolivia',

  // Africa
  Egypt = 'Egypt',
  Ethiopia = 'Ethiopia',
  Morocco = 'Morocco',
  Algeria = 'Algeria',
  Madagascar = 'Madagascar',
  Namibia = 'Namibia',
  Kenya = 'Kenya',
  Mauritius = 'Mauritius',
  SouthAfrica = 'South Africa',
  Uganda = 'Uganda',

  // Asia
  China = 'China',
  India = 'India',
  Japan = 'Japan',
  Korea = 'Korea',
  Thailand = 'Thailand',
  Vietnam = 'Vietnam',
  Indonesia = 'Indonesia',
  Philippines = 'Philippines',

  // Oceania
  Australia = 'Australia',
  NewZealand = 'New Zealand',
  Fiji = 'Fiji',
  Samoa = 'Samoa',
  Tonga = 'Tonga',
  Palau = 'Palau',
}

export const CountryToContinent: Record<Country, Continent> = {
  // Europe
  [Country.Spain]: Continent.Europe,
  [Country.Portugal]: Continent.Europe,
  [Country.UnitedKingdom]: Continent.Europe,
  [Country.Italy]: Continent.Europe,
  [Country.Greece]: Continent.Europe,
  [Country.Netherlands]: Continent.Europe,
  [Country.Belgium]: Continent.Europe,
  [Country.Austria]: Continent.Europe,
  [Country.Switzerland]: Continent.Europe,
  [Country.Germany]: Continent.Europe,
  [Country.France]: Continent.Europe,

  // North America
  [Country.Canada]: Continent.NorthAmerica,
  [Country.USA]: Continent.NorthAmerica,
  [Country.Mexico]: Continent.NorthAmerica,

  // Central America
  [Country.ElSalvador]: Continent.CentralAmerica,
  [Country.CostaRica]: Continent.CentralAmerica,
  [Country.Nicaragua]: Continent.CentralAmerica,
  [Country.Cuba]: Continent.CentralAmerica,
  [Country.PuertoRico]: Continent.CentralAmerica,

  // South America
  [Country.Argentina]: Continent.SouthAmerica,
  [Country.Ecuador]: Continent.SouthAmerica,
  [Country.Chile]: Continent.SouthAmerica,
  [Country.Peru]: Continent.SouthAmerica,
  [Country.Brazil]: Continent.SouthAmerica,
  [Country.Colombia]: Continent.SouthAmerica,
  [Country.Venezuela]: Continent.SouthAmerica,
  [Country.Bolivia]: Continent.SouthAmerica,

  // Africa
  [Country.Egypt]: Continent.Africa,
  [Country.Ethiopia]: Continent.Africa,
  [Country.Morocco]: Continent.Africa,
  [Country.Algeria]: Continent.Africa,
  [Country.Madagascar]: Continent.Africa,
  [Country.Namibia]: Continent.Africa,
  [Country.Kenya]: Continent.Africa,
  [Country.Mauritius]: Continent.Africa,
  [Country.SouthAfrica]: Continent.Africa,
  [Country.Uganda]: Continent.Africa,

  // Asia
  [Country.China]: Continent.Asia,
  [Country.India]: Continent.Asia,
  [Country.Japan]: Continent.Asia,
  [Country.Korea]: Continent.Asia,
  [Country.Thailand]: Continent.Asia,
  [Country.Vietnam]: Continent.Asia,
  [Country.Indonesia]: Continent.Asia,
  [Country.Philippines]: Continent.Asia,

  // Oceania
  [Country.Australia]: Continent.Oceania,
  [Country.NewZealand]: Continent.Oceania,
  [Country.Fiji]: Continent.Oceania,
  [Country.Samoa]: Continent.Oceania,
  [Country.Tonga]: Continent.Oceania,
  [Country.Palau]: Continent.Oceania,
};

export enum IngredientCategory {
  Vegetable = 'Vegetable',
  Fruit = 'Fruit',
  Meat = 'Meat',
  Fish = 'Fish',
  Seafood = 'Seafood',
  Milk = 'Milk',
  Cheese = 'Cheese',
  Grain = 'Grain',
  Legume = 'Legume',
  Nut = 'Nut',
  Seed = 'Seed',
  Herb = 'Herb',
  Spice = 'Spice',
  Oil = 'Oil',
  Sauce = 'Sauce',
  Sweetener = 'Sweetener',
  Beverage = 'Beverage',
  Egg = 'Egg',
  Bakery = 'Bakery',
  Other = 'Other',
}

export const ingredientExamples: Record<IngredientCategory, string[]> = {
  [IngredientCategory.Vegetable]: [
    'Carrot',
    'Broccoli',
    'Spinach',
    'Bell Pepper',
    'Cucumber',
    'Zucchini',
    'Tomato',
    'Cauliflower',
    'Kale',
    'Onion',
    'Garlic',
    'Leek',
    'Mushroom',
    'Asparagus',
    'Eggplant',
    'Radish',
    'Cabbage',
    'Brussels Sprouts',
    'Sweet Potato',
    'Celery',
    'Champignons',
  ],

  [IngredientCategory.Fruit]: [
    'Apple',
    'Banana',
    'Orange',
    'Strawberry',
    'Blueberry',
    'Grapes',
    'Pineapple',
    'Mango',
    'Lemon',
    'Watermelon',
    'Cherry',
    'Peach',
    'Pear',
    'Plum',
    'Raspberry',
    'Blackberry',
    'Kiwi',
    'Papaya',
    'Pomegranate',
    'Cantaloupe',
  ],

  [IngredientCategory.Meat]: [
    'Chicken Breast',
    'Beef Steak',
    'Pork Chop',
    'Lamb',
    'Turkey',
    'Bacon',
    'Sausage',
    'Veal',
    'Duck',
    'Ham',
    'Ground Beef',
    'Chicken Thigh',
    'Pork Shoulder',
    'Lamb Chops',
    'Salami',
    'Prosciutto',
    'Pâté',
    'Turkey Breast',
    'Ribs',
    'Meatballs',
  ],

  [IngredientCategory.Fish]: [
    'Salmon',
    'Tuna',
    'Cod',
    'Trout',
    'Mackerel',
    'Sardine',
    'Herring',
    'Halibut',
    'Snapper',
    'Sea Bass',
    'Tilapia',
    'Anchovy',
    'Pollock',
    'Grouper',
    'Catfish',
    'Swordfish',
    'Redfish',
    'Bass',
    'Bluefish',
    'Flounder',
  ],

  [IngredientCategory.Seafood]: [
    'Shrimp',
    'Crab',
    'Lobster',
    'Clams',
    'Mussels',
    'Scallops',
    'Oysters',
    'Calamari',
    'Cuttlefish',
    'Octopus',
    'Prawns',
    'Crayfish',
    'Sea Urchin',
    'Abalone',
    'Squid',
    'Mahi Mahi',
    'Clam Chowder',
    'Cockles',
    'Langoustine',
    'Conch',
  ],

  [IngredientCategory.Milk]: [
    'Whole Milk',
    'Skim Milk',
    'Semi-Skimmed Milk',
    'Lactose-Free Milk',
    'Oat Milk',
    'Soy Milk',
    'Almond Milk',
    'Rice Milk',
    'Coconut Milk',
    'Goat Milk',
    'Buffalo Milk',
    'Sheep Milk',
    'Hemp Milk',
    'Cashew Milk',
    'Macadamia Milk',
    'Pea Milk',
    'Flax Milk',
    'Quinoa Milk',
    'Tiger Nut Milk',
    'Camel Milk',
  ],

  [IngredientCategory.Cheese]: [
    'Cheddar',
    'Mozzarella',
    'Parmesan',
    'Gouda',
    'Brie',
    'Camembert',
    'Feta',
    'Blue Cheese',
    'Swiss Cheese',
    'Cottage Cheese',
    'Ricotta',
    'Halloumi',
    'Provolone',
    'Emmental',
    'Gruyère',
    'Mascarpone',
    'Paneer',
    'Neufchâtel',
    'Stilton',
    'Roquefort',
    'Cream Cheese',
  ],

  [IngredientCategory.Grain]: [
    'Quinoa',
    'Oats',
    'Wheat Flour',
    'Barley',
    'Rye',
    'Buckwheat',
    'Millet',
    'Couscous',
    'White Rice',
    'Brown Rice',
    'Basmati Rice',
    'Jasmine Rice',
    'Arborio Rice',
    'Wild Rice',
    'Sushi Rice',
    'Black Rice',
    'Red Rice',
    'Parboiled Rice',
    'Spaghetti',
    'Penne',
    'Fusilli',
    'Macaroni',
    'Tagliatelle',
    'Lasagna Sheets',
    'Ravioli',
    'Farfalle',
    'Orzo',
    'Udon',
    'Soba',
    'Ramen',
    'Cavatappi',
    'Gemelli',
    'Pappardelle',
  ],

  [IngredientCategory.Legume]: [
    'Lentils',
    'Chickpeas',
    'Black Beans',
    'Kidney Beans',
    'Green Peas',
    'Soybeans',
    'Pinto Beans',
    'Mung Beans',
    'Fava Beans',
    'Navy Beans',
    'Edamame',
    'Black-eyed Peas',
    'Lupin Beans',
    'Adzuki Beans',
    'Cannellini Beans',
  ],

  [IngredientCategory.Nut]: [
    'Almonds',
    'Walnuts',
    'Cashews',
    'Pecans',
    'Hazelnuts',
    'Macadamia',
    'Pistachios',
    'Brazil Nuts',
    'Chestnuts',
    'Peanuts',
    'Tiger Nuts',
    'Pine Nuts',
    'Coconut',
    'Filberts',
    'Candied Nuts',
  ],

  [IngredientCategory.Seed]: [
    'Chia Seeds',
    'Flax Seeds',
    'Pumpkin Seeds',
    'Sunflower Seeds',
    'Sesame Seeds',
    'Hemp Seeds',
    'Poppy Seeds',
    'Cumin Seeds',
    'Fennel Seeds',
    'Caraway Seeds',
    'Mustard Seeds',
    'Nigella Seeds',
    'Watermelon Seeds',
    'Squash Seeds',
    'Melon Seeds',
  ],

  [IngredientCategory.Herb]: [
    'Basil',
    'Parsley',
    'Cilantro',
    'Thyme',
    'Rosemary',
    'Oregano',
    'Mint',
    'Dill',
    'Chives',
    'Sage',
    'Tarragon',
    'Marjoram',
    'Bay Leaves',
    'Lemongrass',
    'Lovage',
  ],

  [IngredientCategory.Spice]: [
    'Black Pepper',
    'Cinnamon',
    'Turmeric',
    'Paprika',
    'Ginger',
    'Cumin',
    'Nutmeg',
    'Cloves',
    'Coriander',
    'Chili Powder',
    'Cardamom',
    'Saffron',
    'Fennel',
    'Allspice',
    'Star Anise',
  ],

  [IngredientCategory.Oil]: [
    'Olive Oil',
    'Sunflower Oil',
    'Coconut Oil',
    'Canola Oil',
    'Sesame Oil',
    'Avocado Oil',
    'Peanut Oil',
    'Grapeseed Oil',
    'Walnut Oil',
    'Flaxseed Oil',
    'Pumpkin Seed Oil',
    'Hemp Oil',
    'Almond Oil',
    'Safflower Oil',
    'Macadamia Oil',
  ],

  [IngredientCategory.Sauce]: [
    'Tomato Sauce',
    'Soy Sauce',
    'Barbecue Sauce',
    'Pesto',
    'Hollandaise',
    'Mayonnaise',
    'Teriyaki Sauce',
    'Salsa',
    'Hot Sauce',
    'Alfredo Sauce',
    'Chimichurri',
    'Tahini',
    'Hoison Sauce',
    'Ranch Dressing',
    'Worcestershire Sauce',
    'Gochujang',
  ],

  [IngredientCategory.Sweetener]: [
    'Sugar',
    'Honey',
    'Maple Syrup',
    'Agave Nectar',
    'Stevia',
    'Brown Sugar',
    'Molasses',
    'Corn Syrup',
    'Date Syrup',
    'Coconut Sugar',
    'Invert Sugar',
    'Golden Syrup',
    'Rice Syrup',
    'Muscovado Sugar',
    'Palm Sugar',
  ],

  [IngredientCategory.Beverage]: [
    'Water',
    'Coffee',
    'Tea',
    'Milk',
    'Orange Juice',
    'Apple Juice',
    'Grape Juice',
    'Lemonade',
    'Soda',
    'Beer',
    'Wine',
    'Smoothie',
    'Coconut Water',
    'Iced Tea',
    'Hot Chocolate',
    'Espresso',
    'Latte',
    'Cappuccino',
    'Herbal Tea',
    'Kombucha',
  ],

  [IngredientCategory.Egg]: [
    'Chicken Egg',
    'Duck Egg',
    'Quail Egg',
    'Goose Egg',
    'Turkey Egg',
    'Egg White',
    'Egg Yolk',
    'Salted Egg',
    'Century Egg',
    'Ostrich Egg',
    'Emu Egg',
    'Fertilized Egg',
    'Powdered Egg',
    'Liquid Egg',
    'Hard-Boiled Egg',
  ],

  [IngredientCategory.Bakery]: [
    'Bread',
    'Baguette',
    'Croissant',
    'Muffin',
    'Bagel',
    'Scone',
    'Pita',
    'Tortilla',
    'Focaccia',
    'Donut',
    'Ciabatta',
    'Brioche',
    'Pretzel',
    'Roll',
    'Flatbread',
    'English Muffin',
    'Brownie',
    'Cake',
    'Danish Pastry',
    'Cookie',
  ],

  [IngredientCategory.Other]: [
    'Tofu',
    'Tempeh',
    'Seitan',
    'Yeast',
    'Gelatin',
    'Pickles',
    'Kimchi',
    'Vinegar',
    'Miso',
    'Nori',
    'Tahini',
    'Edamame',
    'Coconut Cream',
    'Soy Sauce',
    'Vegetable Broth',
    'Seaweed',
    'Fermented Beans',
    'Wasabi',
    'Capers',
    'Brine',
  ],
};

export interface Ingredient {
  id?: string;
  name: string;
  amount: number;
  unit: Unit;
  category: IngredientCategory;
}

export interface Recipe {
  id: string;
  name: string;
  description: string;
  basePortions: number;

  categories: Category[];
  dietTypes: DietType[];
  ingredients: Ingredient[];
  mealTimes: MealTime[];

  favorite?: boolean;

  seasons?: Season[];
  holidays?: Holiday[];
  occasions?: Occasion[];

  countries?: Country[];
  continents?: Continent[];

  createdAt?: string;
}
